from __future__ import annotations

import shutil
from pathlib import Path

from execution.h3_workflow_builder import (
    H3WorkflowBuilder,
)


class ShotExecutor:

    def __init__(
        self,
        comfy_client,
        project_root,
        comfy_input_dir,
    ):

        self.client = comfy_client

        self.project_root = Path(
            project_root
        )

        self.comfy_input_dir = Path(
            comfy_input_dir
        )

        self.comfy_input_dir.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.builder = (
            H3WorkflowBuilder(
                self.project_root
            )
        )

    def _copy(
        self,
        source,
        prefix,
    ):

        source_path = Path(
            source
        )

        if not source_path.is_file():
            raise FileNotFoundError(
                f"Reference missing: "
                f"{source_path}"
            )

        safe_name = "".join(
            char
            if (
                char.isalnum()
                or char in "._-"
            )
            else "_"
            for char in source_path.name
        )

        destination = (
            self.comfy_input_dir
            / f"{prefix}_{safe_name}"
        )

        shutil.copy2(
            source_path,
            destination,
        )

        return destination.name

    @staticmethod
    def build_prompt(
        shot,
    ):

        # Prefer the structured H3 prompt
        # generated by Shot.
        h3_prompt = shot.get(
            "h3_prompt"
        )

        if h3_prompt:
            return h3_prompt

        parts = []

        for value in (
            shot.get(
                "reference_bindings",
                []
            )
        ):
            if str(value).strip():
                parts.append(
                    str(value)
                )

        for value in (
            shot.get(
                "identity_locks",
                []
            )
        ):
            if str(value).strip():
                parts.append(
                    str(value)
                )

        parts.append(
            str(
                shot.get(
                    "visual_prompt",
                    "",
                )
            )
        )

        return "\n".join(
            part
            for part in parts
            if part.strip()
        )

    def _copy_references(
        self,
        shot,
    ):

        images = [
            self._copy(
                path,
                "ref_image",
            )
            for path in shot.get(
                "reference_images",
                [],
            )[:9]
        ]

        videos = [
            self._copy(
                path,
                "ref_video",
            )
            for path in shot.get(
                "reference_videos",
                [],
            )[:3]
        ]

        # Current shot schema stores all audio refs.
        audio_paths = list(
            shot.get(
                "reference_audio_paths",
                [],
            )
        )

        # The first audio is treated as standalone
        # unless an explicit video-audio mapping exists.
        audio = [
            self._copy(
                path,
                "ref_audio",
            )
            for path in audio_paths[:3]
        ]

        return (
            images,
            videos,
            audio,
        )

    @staticmethod
    def _seed(shot):

        value = shot.get(
            "seed"
        )

        if value is None:
            # Stable deterministic seed per shot.
            return abs(
                hash(
                    shot.get(
                        "shot_id",
                        "h3",
                    )
                )
            ) % (
                2**31 - 1
            )

        return int(value)

    def _download_result(
        self,
        history,
        destination,
        label,
    ):

        outputs = (
            self.client.find_video_outputs(
                history
            )
        )

        if not outputs:
            raise RuntimeError(
                f"H3 {label} produced no video."
            )

        result = outputs[-1]

        return self.client.download_file(
            filename=result[
                "filename"
            ],
            subfolder=result[
                "subfolder"
            ],
            file_type=result[
                "type"
            ],
            destination=destination,
        )

    def execute_native_ref2va(
        self,
        shot,
        output_dir,
    ):

        (
            image_files,
            video_files,
            audio_files,
        ) = self._copy_references(
            shot
        )

        workflow = (
            self.builder.build_ref2va(
                prompt=self.build_prompt(
                    shot
                ),

                image_files=image_files,

                video_files=video_files,

                audio_files=audio_files,

                width=int(
                    shot.get(
                        "width",
                        1344,
                    )
                ),

                height=int(
                    shot.get(
                        "height",
                        768,
                    )
                ),

                frames=int(
                    shot.get(
                        "frames_per_shot",
                        124,
                    )
                ),

                steps=int(
                    shot.get(
                        "steps",
                        14,
                    )
                ),

                seed=self._seed(
                    shot
                ),

                output_prefix=(
                    "h3/ref2va/"
                    + str(
                        shot[
                            "shot_id"
                        ]
                    )
                ),
            )
        )

        prompt_id = (
            self.client.queue_prompt(
                workflow
            )
        )

        history = (
            self.client.wait_for_prompt(
                prompt_id,
                timeout=7200,
            )
        )

        destination = (
            Path(output_dir)
            / f"{shot['shot_id']}.mp4"
        )

        return self._download_result(
            history,
            destination,
            "Ref2VA",
        )
