from pathlib import Path
import socket
import subprocess
import sys


PROJECT = Path(
    "/kaggle/working/LTX-13B-AI-Video-Model"
)

COMFY = PROJECT / "ComfyUI"

BOOTSTRAP = (
    PROJECT / "kaggle" / "bootstrap.py"
)

TUNNEL = (
    PROJECT
    / "kaggle"
    / "start_comfyui_tunnel.py"
)

EXTRA_PATHS = (
    COMFY / "extra_model_paths.yaml"
)

PORT = 8188


MODEL_FILES = {
    "ltx_q4":
        "LTXV-13B-0.9.8-distilled-Q4_K_M.gguf",

    "vae":
        "LTXV-13B-0.9.8-distilled-VAE.safetensors",

    "t5":
        "t5-v1_1-xxl-encoder-Q4_K_M.gguf",

    "detailer":
        "ltxv-098-ic-lora-detailer-comfyui.safetensors",

    "upscaler":
        "ltxv-spatial-upscaler-0.9.8.safetensors",
}


def run(command, cwd=None):
    print(
        "\n$",
        " ".join(map(str, command)),
    )

    subprocess.run(
        command,
        cwd=cwd,
        check=True,
    )


def check_gpu():

    import torch

    print("=" * 70)
    print("GPU / CUDA CHECK")
    print("=" * 70)

    print("Torch:", torch.__version__)
    print("CUDA:", torch.version.cuda)
    print(
        "CUDA available:",
        torch.cuda.is_available(),
    )

    if not torch.cuda.is_available():
        raise RuntimeError(
            "CUDA is unavailable."
        )

    count = torch.cuda.device_count()

    print("GPU count:", count)

    if count < 2:
        raise RuntimeError(
            "This project requires 2 GPUs."
        )

    for i in range(count):
        print(
            f"GPU {i}:",
            torch.cuda.get_device_name(i),
        )


def find_model(filename):

    root = Path("/kaggle/input")

    matches = list(
        root.rglob(filename)
    )

    if not matches:
        raise FileNotFoundError(
            f"\nModel file not found:\n"
            f"{filename}\n"
            f"Search root: {root}"
        )

    if len(matches) > 1:
        print(
            f"WARNING: multiple copies found "
            f"for {filename}"
        )

    path = matches[0]

    print(
        f"FOUND {filename}\n"
        f"  {path}"
    )

    return path


def find_all_models():

    print()
    print("=" * 70)
    print("SEARCHING KAGGLE MODEL DATASETS")
    print("=" * 70)

    models = {}

    for key, filename in MODEL_FILES.items():

        models[key] = find_model(
            filename
        )

    return models


def create_model_paths(models):

    ltx_q4 = models["ltx_q4"]
    vae = models["vae"]
    t5 = models["t5"]
    detailer = models["detailer"]
    upscaler = models["upscaler"]

    config = f"""# Automatically generated by kaggle/launch.py
# Do not edit manually.

ltx_project:
    is_default: true

    diffusion_models: |
        {ltx_q4.parent}

    unet: |
        {ltx_q4.parent}

    text_encoders: |
        {t5.parent}

    clip: |
        {t5.parent}

    vae: |
        {vae.parent}

    loras: |
        {detailer.parent}

    upscale_models: |
        {upscaler.parent}
"""

    EXTRA_PATHS.write_text(
        config,
        encoding="utf-8",
    )

    print()
    print(
        "✅ Created ComfyUI model configuration:"
    )

    print(EXTRA_PATHS)


def verify_nodes():

    required = [
        "ComfyUI-GGUF",
        "ComfyUI-LTXVideo",
        "ComfyUI-VideoHelperSuite",
        "rgthree-comfy",
    ]

    custom_nodes = (
        COMFY / "custom_nodes"
    )

    print()
    print("=" * 70)
    print("CUSTOM NODE CHECK")
    print("=" * 70)

    for node in required:

        path = custom_nodes / node

        if not path.exists():
            raise RuntimeError(
                f"Missing custom node:\n{node}"
            )

        print(
            f"{node:30} OK"
        )


def ensure_repository():

    if PROJECT.exists():

        print(
            "✅ Project repository already exists."
        )

        return

    print(
        "Repository not found."
    )

    print(
        "This means Kaggle started a new "
        "working session."
    )

    print(
        "The notebook startup cell will clone "
        "the repository first."
    )

    raise RuntimeError(
        "Repository must be cloned before "
        "launch.py is executed."
    )


def ensure_comfyui():

    main_py = COMFY / "main.py"

    if main_py.exists():

        print(
            "✅ ComfyUI installation found."
        )

        return

    print(
        "⚠️ ComfyUI not found."
    )

    print(
        "Running bootstrap..."
    )

    run(
        [
            sys.executable,
            str(BOOTSTRAP),
        ]
    )

    if not main_py.exists():

        raise RuntimeError(
            "Bootstrap completed but "
            "ComfyUI/main.py was not found."
        )


def port_open():

    try:

        with socket.create_connection(
            ("127.0.0.1", PORT),
            timeout=1,
        ):
            return True

    except OSError:

        return False


def start_tunnel():

    if not TUNNEL.exists():

        raise FileNotFoundError(
            f"Tunnel launcher not found:\n"
            f"{TUNNEL}"
        )

    print()
    print("=" * 70)
    print(
        "STARTING COMFYUI + CLOUDFLARE"
    )
    print("=" * 70)

    run(
        [
            sys.executable,
            "-u",
            str(TUNNEL),
        ]
    )
    
def ensure_comfy_runtime_dependencies():
    """
    Install missing ComfyUI runtime dependencies required by
    the currently installed ComfyUI version.

    Torch/CUDA packages are intentionally NOT modified.
    """

    import importlib.util

    module_to_package = {
        "comfy_aimdo": "comfy-aimdo",
        "comfy_kitchen": "comfy-kitchen",
        "torchsde": "torchsde",
    }

    missing_packages = []

    for module_name, package_name in module_to_package.items():

        if importlib.util.find_spec(module_name) is None:
            missing_packages.append(package_name)

    if not missing_packages:
        print(
            "✅ ComfyUI runtime dependencies are present."
        )
        return

    print()
    print("=" * 70)
    print(
        "INSTALLING MISSING COMFYUI RUNTIME DEPENDENCIES"
    )
    print("=" * 70)

    requirements = (
        COMFY / "requirements.txt"
    )

    if not requirements.exists():
        raise FileNotFoundError(
            f"ComfyUI requirements file not found:\n"
            f"{requirements}"
        )

    lines = requirements.read_text(
        encoding="utf-8"
    ).splitlines()

    package_lookup = {
        line.split("==")[0]
             .split(">=")[0]
             .split("<=")[0]
             .split(">")[0]
             .split("<")[0]
             .strip()
             .lower(): line.strip()
        for line in lines
        if line.strip()
        and not line.strip().startswith("#")
    }

    packages_to_install = []

    for package_name in missing_packages:

        normalized = package_name.lower()

        if normalized in package_lookup:
            packages_to_install.append(
                package_lookup[normalized]
            )
        else:
            # torchsde may not be present in a particular
            # requirements revision, so allow pip to resolve it.
            packages_to_install.append(
                package_name
            )

    print(
        "Installing:",
        packages_to_install,
    )

    subprocess.run(
        [
            sys.executable,
            "-m",
            "pip",
            "install",
            *packages_to_install,
        ],
        check=True,
    )

    print(
        "✅ Missing ComfyUI runtime dependencies installed."
    )
def main():

    print()
    print("=" * 70)
    print(
        "LTX-13B AI VIDEO SYSTEM"
    )
    print(
        "ONE-CELL STARTUP"
    )
    print("=" * 70)

    check_gpu()

    ensure_repository()

    ensure_comfyui()

    ensure_comfy_runtime_dependencies()
    
    models = find_all_models()

    create_model_paths(
        models
    )

    verify_nodes()

    if port_open():

        print()
        print(
            "✅ ComfyUI is already running "
            "on port 8188."
        )

        return

    start_tunnel()


if __name__ == "__main__":
    main()
